<?php

/* 
 * The MIT License
 *
 * Copyright 2016 Andrei Olteanu andrei@flashsoft.ro.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */


class LimeSImportGenerate {

    public function __construct() {
        
    }

    public function textExport() {
        header('Content-Type: text/plain');
        $counts = [0 => 0, 1 => 0, 2 => 0,];
        // Used for generating codes for Lime
        // Default G-> group , Q -> Question, A -> Answer
        $customCodes = [ 0 => "G", 1 => "Q", 2 => "A",];


        $groupBegin = 'G	%s	%s	1			ro																																																																																																																										';
        $questionBegin = 'Q	L	%s	1	%s		ro		Y	N		1																1																																																																															1					1																	';
        $ansBegin = 'A	0	%s		%s		ro																																																																																																																										';

        foreach ($this->impArr as $el) {

            if (preg_match("/#1#.*/", $el, $match)) {
                echo sprintf($groupBegin, $customCodes[0] . $counts[0], trim(preg_replace('/\t+/', '', substr($match[0], 3))));
                echo PHP_EOL;
                $counts[0] ++;
            } else if (preg_match("/#2#.*/", $el, $match2)) {
                echo sprintf($questionBegin, $customCodes[1] . $counts[1], trim(preg_replace('/\t+/', '', substr($match2[0], 3))));
                echo PHP_EOL;
                $counts[1] ++;
                $counts[2] = 0;
            } else if (preg_match("/#3#.*/", $el, $match3)) {
                echo sprintf($ansBegin, $customCodes[2] . $counts[2], trim(preg_replace('/\t+/', '', substr($match3[0], 3))));
                echo PHP_EOL;
                $counts[2] ++;
            }
        }
    }

    public function qXMLExport() {

        // Counts for arry Type #1,#2,#3
        $counts = [0 => 0, 1 => 0, 2 => 0,];
        // Used for generating codes for Lime
        // Default G-> group , Q -> Question, A -> Answer
        $customCodes = [ 0 => "G", 1 => "Q", 2 => "A",];

        $groupBegin = '<section id="%s">
    <sectionInfo>
      <position>title</position>
      <text>%s</text>
      <administration>self</administration>
    </sectionInfo>';
        $groupEnd = '</section>';
        $questionBegin = '<question>
      <text>%s</text>
      <response varName="%s">
        <fixed>';
        $questionEnd = ' </fixed>
      </response>
    </question>';
        $ansBody = '          <category>
            <label>%s</label>
            <value>%s</value>
          </category>';


        echo '<pre>';
        foreach ($this->impArr as $el) {

            if (preg_match("/#1#.*/", $el, $match)) {
                if ($counts[0] !== 0) {
                    echo $groupEnd;
                }
                echo sprintf($groupBegin, $customCodes[0] . $counts[0], substr($match[0], 3));
                $counts[0] ++;
                $counts[1] = 0;
            } else if (preg_match("/#2#.*/", $el, $match2)) {
                if ($counts[1] !== 0) {
                    echo $questionEnd;
                }
                echo sprintf($questionBegin, $customCodes[1] . $counts[1], substr($match2[0], 3));
                $counts[1] ++;
                $counts[2] = 0;
            } else if (preg_match("/#3#.*/", $el, $match3)) {
                echo sprintf($ansBody, $customCodes[2] . $counts[2], substr($match3[0], 3));
                $counts[2] ++;
            }
        }
        echo $groupEnd;
        echo '</pre>';
    }

    protected $impArr = ['#1#EXIGENŢE CANTITATIVE / TEMPORALE:	',
        '#2#01.	Trebuie să lucraţi foarte repede? ',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată	',
        '#2#02.	Munca dumneavoastră este distribuită neuniform, astfel încât există momente de supraîncărcare? ',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#2#03.	Cât de des se întâmplă să nu aveţi timp să vă finalizaţi complet sarcinile?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#2#04. Sunt situaţii când trebuie să faceţi ore suplimentare? ',
        '#3#      Întotdeauna',
        '#3#      Deseori',
        '#3#      Uneori',
        '#3#      Rareori',
        '#3#      Niciodată / Aproape niciodată',
        '#1#EXIGENŢE COGNITIVE: 	',
        '#2#05.	Trebuie să fiţi atent la mai multe lucruri în timp ce lucraţi?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#2#06.	Munca dumneavoastră necesită să vă reamintiţi multe lucruri?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#2#07.	În munca dumneavoastră trebuie să veniţi cu idei noi?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#2#08.	La locul dumneavoastră de muncă trebuie să luaţi decizii foarte importante?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#1#EXIGENŢE EMOŢIONALE: 	',
        '#2#09.	Munca dumneavoastră vă pune în situaţii de tulburare emoţională? ',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#2#10.	Munca dumneavoastră necesită implicare emoţională?',
        '#3#       Într-o foarte mare măsură',
        '#3#       În mare măsură',
        '#3#       Oarecum',
        '#3#       În mică măsură',
        '#3#       În foarte mică măsură',
        '#2#11.	Vă implicaţi emoţional în munca dumneavoastră?',
        '#3#       Într-o foarte mare măsură',
        '#3#       În mare măsură',
        '#3#       Oarecum',
        '#3#       În mică măsură',
        '#3#       În foarte mică măsură',
        '#1#EXIGENŢE DE ASCUNDERE A EMOŢIILOR:	',
        '#2#12.	În munca dumneavoastră este necesar să nu vă expuneţi părerea proprie?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#2#13.	În munca dumneavoastră este necesar să vă ascundeţi sentimentele?',
        '#3#       Într-o foarte mare măsură',
        '#3#       În mare măsură',
        '#3#       Oarecum',
        '#3#       În mică măsură',
        '#3#       În foarte mică măsură	',
        '#1#EXIGENŢE SENZORIAL - PERCEPTIVE: 	',
        '#2#14.	Activitatea dumneavoastră necesită o vedere bună şi precisă?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#2#15.	Activitatea dumneavoastră necesită un auz bun ?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#2#16.	În activitatea dumneavoastră este necesar să vă controlaţi conştient mişcările?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#2#17.	Activitatea dumneavoastră necesită atenţie permanentă?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#2#18.	Activitatea dumneavoastră necesită un nivel înalt de precizie?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată	',
        '#2#19.	Activitatea dumneavoastră necesită ascultarea cu atenţie a zgomotelor provenite de la maşină echipament tehnic / instalaţie sau a   informaţiilor provenite din comunicarea verbală ?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată	',
        '#1#EXIGENŢE PROVENIND DIN RESPONSABILITĂŢI ÎN ACTIVITATE	',
        '#2#20.	Erorile dumneavoastră în activitate pot cauza accidentarea altor persoane?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#2#21.	Erorile dumneavoastră în activitate pot cauza propria accidentare?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#2#22.	Erorile dumneavoastră în activitate pot cauza pierderi financiare prin  avariere de echipamente sau prin compromiterea rezultatelor activităţii?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#1#INFLUENŢA ÎN ACTIVITATE:	',
        '#2#23.	În general, aveţi o influenţă mare în ceea ce priveşte activitatea dumneavoastră?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#2#24.	Puteţi să vă influenţaţi ritmul de lucru?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#2#25.	Puteţi să influenţaţi modul în care (CUM să) vă realizaţi sarcinile?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#2#26.	Puteţi să influenţaţi ceea ce faceţi în munca dumneavoastră?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#1#POSIBILITĂŢI DE DEZVOLTARE	',
        '#2#27.	Munca dumneavoastră este variată?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#2#28.	Munca dumneavoastră necesită iniţiativă?',
        '#3#       Într-o foarte mare măsură',
        '#3#       În mare măsură',
        '#3#       Oarecum',
        '#3#       În mică măsură',
        '#3#       În foarte mică măsură',
        '#2#29.	În munca dumneavoastră, aveţi posibilitatea să învăţaţi lucruri noi?',
        '#3#       Într-o foarte mare măsură',
        '#3#       În mare măsură',
        '#3#       Oarecum',
        '#3#       În mică măsură',
        '#3#       În foarte mică măsură',
        '#2#30.	Vă puteţi utiliza aptitudinile şi experienţa în muncă?',
        '#3#       Într-o foarte mare măsură',
        '#3#       În mare măsură',
        '#3#       Oarecum',
        '#3#       În mică măsură',
        '#3#       În foarte mică măsură',
        '#1#GRADUL DE LIBERTATE PRIVIND PERIOADELE DE REPAUS ŞI ODIHNĂ	',
        '#2#31.	Aveţi posibilitatea să decideţi când să luaţi pauză?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#2#32.	Vă puteţi lua concediu atunci când doriţi?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#2#33.	Vă puteţi părăsi locul de muncă pentru a vorbi cu un coleg?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#2#34.	În cazul în care aveţi treburi personale de rezolvat, puteţi să vă părăsiţi locul de muncă pentru o jumătate de oră, fără permisiune specială?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#1#IMPORTANŢA ACTIVITĂŢII	',
        '#2#35.	Consideraţi că munca dumneavoastră are un înţeles?',
        '#3#       Într-o foarte mare măsură',
        '#3#       În mare măsură',
        '#3#       Oarecum',
        '#3#       În mică măsură',
        '#3#       În foarte mică măsură',
        '#2#36.	Aveţi sentimentul că munca dumneavoastră este importantă?',
        '#3#       Într-o foarte mare măsură',
        '#3#       În mare măsură',
        '#3#       Oarecum',
        '#3#       În mică măsură',
        '#3#       În foarte mică măsură',
        '#2#37.	Vă simţiţi motivat şi implicat în muncă?',
        '#3#       Într-o foarte mare măsură',
        '#3#       În mare măsură',
        '#3#       Oarecum',
        '#3#       În mică măsură',
        '#3#       În foarte mică măsură',
        '#1#IMPLICARE AFECTIVĂ ÎN ACTIVITATE	',
        '#2#38.	Vă doriţi să rămâneţi la locul actual de muncă pentru tot restul vieţii active?',
        '#3#       Într-o foarte mare măsură',
        '#3#       În mare măsură',
        '#3#       Oarecum',
        '#3#       În mică măsură',
        '#3#       În foarte mică măsură',
        '#2#39.	Vă face plăcere să povestiţi altor persoane despre locul dumneavoastră de muncă?',
        '#3#       Într-o foarte mare măsură',
        '#3#       În mare măsură',
        '#3#       Oarecum',
        '#3#       În mică măsură',
        '#3#       În foarte mică măsură',
        '#2#40.	Consideraţi că problemele de la locul de muncă sunt şi ale dumneavoastră?',
        '#3#       Într-o foarte mare măsură',
        '#3#       În mare măsură',
        '#3#       Oarecum',
        '#3#       În mică măsură',
        '#3#       În foarte mică măsură',
        '#2#41.	Aveţi sentimentul că locul de muncă are o mare importanţă pentru dumneavoastră?',
        '#3#       Într-o foarte mare măsură',
        '#3#       În mare măsură',
        '#3#       Oarecum',
        '#3#       În mică măsură',
        '#3#       În foarte mică măsură',
        '#1#GRADUL DE INFORMARE	',
        '#2#42.	La locul dumneavoastră de muncă, sunteţi informat din timp cu privire la deciziile importante, schimbările sau planurile de viitor?',
        '#3#       Într-o foarte mare măsură',
        '#3#       În mare măsură',
        '#3#       Oarecum',
        '#3#       În mică măsură',
        '#3#       În foarte mică măsură',
        '#2#43.	Primiţi toate informaţiile de care aveţi nevoie pentru a vă îndeplini bine sarcinile?',
        '#3#       Într-o foarte mare măsură',
        '#3#       În mare măsură',
        '#3#       Oarecum',
        '#3#       În mică măsură',
        '#3#       În foarte mică măsură',
        '#1#CLARITATEA ROLULUI	',
        '#2#44.	Ştiţi exact câtă autoritate (influenţă) aveţi la locul de muncă?',
        '#3#       Într-o foarte mare măsură',
        '#3#       În mare măsură',
        '#3#       Oarecum',
        '#3#       În mică măsură',
        '#3#       În foarte mică măsură',
        '#2#45.	Munca dumneavoastră are obiective clare?',
        '#3#       Într-o foarte mare măsură',
        '#3#       În mare măsură',
        '#3#       Oarecum',
        '#3#       În mică măsură',
        '#3#       În foarte mică măsură',
        '#2#46.	Vă cunoaşteţi exact responsabilităţile la locul de muncă?',
        '#3#       Într-o foarte mare măsură',
        '#3#       În mare măsură',
        '#3#       Oarecum',
        '#3#       În mică măsură',
        '#3#       În foarte mică măsură',
        '#2#47.	Ştiţi exact ce se aşteaptă de la dumneavoastră la locul de muncă?',
        '#3#       Într-o foarte mare măsură',
        '#3#       În mare măsură',
        '#3#       Oarecum',
        '#3#       În mică măsură',
        '#3#       În foarte mică măsură',
        '#1#CONFLICTE DE ROL	',
        '#2#48.	Ceea ce faceţi la locul de muncă este recunoscut de unele persoane şi  nu este recunoscut de altele?',
        '#3#       Într-o foarte mare măsură',
        '#3#       În mare măsură',
        '#3#       Oarecum',
        '#3#       În mică măsură',
        '#3#       În foarte mică măsură',
        '#2#49.	În munca dumneavoastră vă sunt adresate cerinţe contradictorii?',
        '#3#       Într-o foarte mare măsură',
        '#3#       În mare măsură',
        '#3#       Oarecum',
        '#3#       În mică măsură',
        '#3#       În foarte mică măsură',
        '#2#50.	Uneori, trebuie să faceţi lucruri care erau făcute, în mod obişnuit, altfel?',
        '#3#       Într-o foarte mare măsură',
        '#3#       În mare măsură',
        '#3#       Oarecum',
        '#3#       În mică măsură',
        '#3#       În foarte mică măsură',
        '#2#51.	Uneori, trebuie să faceţi lucruri care nu vi se pare necesare?',
        '#3#       Într-o foarte mare măsură',
        '#3#       În mare măsură',
        '#3#       Oarecum',
        '#3#       În mică măsură',
        '#3#       În foarte mică măsură',
        '#1#STIL DE CONDUCERE',
        '#2#52.	 În ce măsură apreciaţi că superiorul dumneavoastră se asigură că membrii personalului (colectivului) beneficiază de oportunităţi de dezvoltare?',
        '#3#       Într-o foarte mare măsură',
        '#3#       În mare măsură',
        '#3#       Oarecum',
        '#3#       În mică măsură',
        '#3#       În foarte mică măsură	',
        '#2#53.	În ce măsură apreciaţi că superiorul dumneavoastră acordă prioritate satisfacţiei în muncă (a personalului)?',
        '#3#       Într-o foarte mare măsură',
        '#3#       În mare măsură',
        '#3#       Oarecum',
        '#3#       În mică măsură',
        '#3#       În foarte mică măsură	',
        '#2#54.	În ce măsură apreciaţi că superiorul dumneavoastră este capabil de o bună planificare a muncii?',
        '#3#       Într-o foarte mare măsură',
        '#3#       În mare măsură',
        '#3#       Oarecum',
        '#3#       În mică măsură',
        '#3#       În foarte mică măsură	',
        '#2#55.	În ce măsură apreciaţi că superiorul dumneavoastră este capabil să rezolve conflictele la locul de muncă?',
        '#3#       Într-o foarte mare măsură',
        '#3#       În mare măsură',
        '#3#       Oarecum',
        '#3#       În mică măsură',
        '#3#       În foarte mică măsură	',
        '#1#SUPORT SOCIAL	',
        '#2#56.	Cât de des primiţi ajutor şi suport din partea colegilor dumneavoastră?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#2#57.	Cât de des sunt colegii dumneavoastră dispuşi să vă asculte problemele legate de muncă?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#2#58.	Cât de des primiţi ajutor şi suport de la superiorul imediat?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#2#59.	Cât de des este superiorul dumneavoastră dispus să vă asculte problemele legate de muncă?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#1#FEEDBACK ÎN MUNCĂ	',
        '#2#60.	Cât de des superiorul discută cu dumneavoastră despre modul în care v-aţi îndeplinit sarcinile?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#2#61.	Cât de des colegii discută cu dumneavoastră despre modul în care v-aţi îndeplinit sarcinile?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#1#POSIBILITĂŢI DE COMUNICARE	',
        '#2#62.	Lucraţi izolat de ceilalţi colegi?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#2#63.	Puteţi discuta cu colegii în timpul desfăşurării activităţii?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#1#SPIRIT DE ECHIPĂ	',
        '#2#64.	Există o atmosferă bună între dumneavoastră şi colegi?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#2#65.	Există o bună cooperare între colegi la locul dumneavoastră de muncă?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#2#66.	Vă simţiţi parte a unui colectiv la locul dumneavoastră de muncă?',
        '#3#       Întotdeauna',
        '#3#       Deseori',
        '#3#       Uneori',
        '#3#       Rareori',
        '#3#       Niciodată / Aproape niciodată',
        '#1#LIPSA SIGURANŢEI LOCULULUI DE MUNCĂ',
        '#2#67.	Sunteţi îngrijorat în legătură cu şomajul?',
        '#3#       da',
        '#3#       nu',
        '#2#68.	Sunteţi îngrijorat în legătură cu noua tehnologie, care v-ar putea face nefolositor?',
        '#3#       da',
        '#3#       nu',
        '#2#69.	Sunteţi îngrijorat în legătură cu va fi dificil pentru dumneavoastră să vă găsiţi alt loc de muncă, în cazul şomajului?',
        '#3#       da',
        '#3#       nu',
        '#2#70.	Sunteţi îngrijorat în legătură cu transferul la alt loc de muncă, împotriva voinţei dumneavoastră?',
        '#3#       da',
        '#3#       nu',
        '#1#SATISFACŢIA ÎN MUNCĂ',
        '#2#71.	Cât de satisfăcut sunteţi de perspectivele muncii dumneavoastră?',
        '#3#       Foarte satisfăcut',
        '#3#       Satisfăcut',
        '#3#       Nesatisfăcut',
        '#3#       Foarte nesatisfăcut',
        '#3#       Nu e relevant',
        '#2#72.	Cât de satisfăcut sunteţi de condiţiile fizice de muncă?',
        '#3#       Foarte satisfăcut',
        '#3#       Satisfăcut',
        '#3#       Nesatisfăcut',
        '#3#       Foarte nesatisfăcut',
        '#3#       Nu e relevant',
        '#2#73.	Cât de satisfăcut sunteţi de modul în care sunt utilizate capacităţile dumneavoastră?',
        '#3#       Foarte satisfăcut',
        '#3#       Satisfăcut',
        '#3#       Nesatisfăcut',
        '#3#       Foarte nesatisfăcut',
        '#3#       Nu e relevant',
        '#2#74.	Cât de satisfăcut sunteţi de munca dumneavoastră, în general, luând în considerare întregul ansamblu?',
        '#3#       Foarte satisfăcut',
        '#3#       Satisfăcut',
        '#3#       Nesatisfăcut',
        '#3#       Foarte nesatisfăcut',
        '#3#       Nu e relevant',
        '#1#SĂNĂTATEA GENERALĂ	',
        '#2#75.	În general, sănătatea dumneavoastră este...',
        '#3#       Excelentă',
        '#3#       Foarte bună',
        '#3#       Bună',
        '#3#       Satisfăcătoare',
        '#3#       Proastă',
        '#1#Cât de ADEVĂRATĂ sau FALSĂ este fiecare dintre următoarele afirmaţii în cazul dvs.?',
        '#2#76.	Se pare că mă îmbolnăvesc mai des decât alte persoane.',
        '#3#      Categoric adevărat',
        '#3#      Relativ adevărat',
        '#3#      Nu ştiu',
        '#3#      Relativ fals',
        '#3#      Categoric fals',
        '#2#77.	Sunt la fel de sănătos ca şi ceilalţi pe care îi cunosc.',
        '#3#       Categoric adevărat',
        '#3#       Relativ adevărat',
        '#3#       Nu ştiu',
        '#3#       Relativ fals',
        '#3#       Categoric fals',
        '#2#78.	Mă aştept ca sănătatea mea să se înrăutăţească.',
        '#3#       Categoric adevărat',
        '#3#       Relativ adevărat ',
        '#3#       Nu ştiu',
        '#3#       Relativ fals',
        '#3#       Categoric fals',
        '#2#79.	Sănătatea mea este excelentă.',
        '#3#       Categoric adevărat',
        '#3#       Relativ adevărat',
        '#3#       Nu ştiu',
        '#3#       Relativ fals',
        '#3#       Categoric fals',
        '#1#SĂNĂTATEA MENTALĂ',
        '#2#80.	În cursul ultimelor 4 săptămâni, dumneavoastră aţi fost foarte nervos?',
        '#3#      Tot timpul',
        '#3#      Cea mai mare perioadă din timp',
        '#3#      O bună parte din timp',
        '#3#      Oarecum',
        '#3#      O perioadă scurtă',
        '#3#      Deloc',
        '#2#81.	În cursul ultimelor 4 săptămâni, dumneavoastră aţi simţit că nimic nu v-ar putea înveseli?',
        '#3#      Tot timpul',
        '#3#      Cea mai mare perioadă din timp',
        '#3#      O bună parte din timp',
        '#3#      Oarecum',
        '#3#      O perioadă scurtă',
        '#3#      Deloc',
        '#2#82.	În cursul ultimelor 4 săptămâni, dumneavoastră v-aţi simţit calm şi liniştit?',
        '#3#      Tot timpul',
        '#3#      Cea mai mare perioadă din timp',
        '#3#      O bună parte din timp',
        '#3#      Oarecum',
        '#3#      O perioadă scurtă',
        '#3#      Deloc',
        '#2#83.	În cursul ultimelor 4 săptămâni, dumneavoastră v-aţi simţit deprimat?',
        '#3#      Tot timpul',
        '#3#      Cea mai mare perioadă din timp',
        '#3#      O bună parte din timp',
        '#3#      Oarecum',
        '#3#      O perioadă scurtă',
        '#3#      Deloc',
        '#2#84.	În cursul ultimelor 4 săptămâni, dumneavoastră v-aţi simţit fericit?',
        '#3#      Tot timpul',
        '#3#      Cea mai mare perioadă din timp',
        '#3#      O bună parte din timp',
        '#3#      Oarecum',
        '#3#      O perioadă scurtă',
        '#3#      Deloc',
        '#1#VITALITATE',
        '#2#85.	 Cât de des în cursul ultimelor 4 săptămâni, dumneavoastră v-aţi simţit plin de vigoare?',
        '#3#      Tot timpul',
        '#3#      Cea mai mare perioadă din timp',
        '#3#      O bună parte din timp',
        '#3#      Oarecum',
        '#3#      O perioadă scurtă',
        '#3#      Deloc',
        '#2#86.	Cât de des în cursul ultimelor 4 săptămâni, dumneavoastră aţi avut multă energie?',
        '#3#      Tot timpul',
        '#3#      Cea mai mare perioadă din timp',
        '#3#      O bună parte din timp',
        '#3#      Oarecum',
        '#3#      O perioadă scurtă',
        '#3#      Deloc',
        '#2#87.	Cât de des în cursul ultimelor 4 săptămâni, dumneavoastră v-aţi simţit epuizat?',
        '#3#      Tot timpul',
        '#3#      Cea mai mare perioadă din timp',
        '#3#      O bună parte din timp',
        '#3#      Oarecum',
        '#3#      O perioadă scurtă',
        '#3#      Deloc',
        '#2#88.	Cât de des în cursul ultimelor 4 săptămâni, dumneavoastră v-aţi simţit obosit?',
        '#3#      Tot timpul',
        '#3#      Cea mai mare perioadă din timp',
        '#3#      O bună parte din timp',
        '#3#      Oarecum',
        '#3#      O perioadă scurtă',
        '#3#      Deloc',
        '#1#STRES COMPORTAMENTAL',
        '#2#89.	 Pe parcursul ultimelor 4 săptămâni nu am fost capabil să relaţionez / comunic cu alte persoane.',
        '#3#       Corect',
        '#3#       Destul de corect',
        '#3#       Oarecum corect',
        '#3#       Destul de incorect',
        '#3#       Incorect',
        '#2#90.	Pe parcursul ultimelor 4 săptămâni nu am avut timp să mă relaxez.',
        '#3#        Corect',
        '#3#        Destul de corect',
        '#3#        Oarecum corect',
        '#3#        Destul de incorect',
        '#3#        Incorect',
        '#2#91.	Pe parcursul ultimelor 4 săptămâni am fost destul de susceptibil (sensibil).',
        '#3#        Corect',
        '#3#        Destul de corect',
        '#3#        Oarecum corect',
        '#3#        Destul de incorect',
        '#3#        Incorect',
        '#2#92.	Pe parcursul ultimelor 4 săptămâni am fost lipsit de iniţiativă.',
        '#3#       Corect',
        '#3#       Destul de corect',
        '#3#       Oarecum corect',
        '#3#       Destul de incorect',
        '#3#       Incorect',
        '#1#STRES SOMATIC',
        '#2#93.	Cât de des, pe parcursul ultimelor 4 săptămâni aţi avut dureri sau probleme cu stomacul?',
        '#3#      Tot timpul',
        '#3#      Deseori',
        '#3#      Uneori',
        '#3#      Rareori',
        '#3#      Niciodată / Aproape niciodată	',
        '#2#94.	Cât de des, pe parcursul ultimelor 4 săptămâni aţi avut dureri de piept?',
        '#3#      Tot timpul',
        '#3#      Deseori',
        '#3#      Uneori',
        '#3#      Rareori',
        '#3#      Niciodată / Aproape niciodată	',
        '#2#95.	...v-aţi simţit ameţit?',
        '#3#      Tot timpul',
        '#3#      Deseori',
        '#3#      Uneori',
        '#3#      Rareori',
        '#3#      Niciodată / Aproape niciodată',
        '#2#96.	Cât de des, pe parcursul ultimelor 4 săptămâni aţi simţit tensiuni în unele grupe musculare?',
        '#3#      Tot timpul',
        '#3#      Deseori',
        '#3#      Uneori',
        '#3#      Rareori',
        '#3#      Niciodată / Aproape niciodată	',
        '#1#STRES COGNITIV',
        '#2#97.	Cât de des, pe parcursul ultimelor 4 săptămâni aţi avut probleme de concentrare?',
        '#3#      Tot timpul',
        '#3#      Deseori',
        '#3#      Uneori',
        '#3#      Rareori',
        '#3#      Niciodată / Aproape niciodată',
        '#2#98.	Cât de des, pe parcursul ultimelor 4 săptămâni aţi avut dificultăţi în luarea  deciziilor?',
        '#3#      Tot timpul',
        '#3#      Deseori',
        '#3#      Uneori',
        '#3#      Rareori',
        '#3#      Niciodată / Aproape niciodată',
        '#2#99.	Cât de des, pe parcursul ultimelor 4 săptămâni aţi avut dificultăţi de reamintire?',
        '#3#      Tot timpul',
        '#3#      Deseori',
        '#3#      Uneori',
        '#3#      Rareori',
        '#3#      Niciodată / Aproape niciodată',
        '#2#100.	Cât de des, pe parcursul ultimelor 4 săptămâni v-a fost dificil să gândiţi cu claritate?',
        '#3#      Tot timpul',
        '#3#      Deseori',
        '#3#      Uneori',
        '#3#      Rareori',
        '#3#      Niciodată / Aproape niciodată	',];

}

// 
// Example usage
// 
// $s = new LimeSImportGenerate();
// $s.textExport();





